In [3]:
import einops
import numpy as np

In [ ]:
A = np.arange(12).reshape(3,4) # 3 by 4 matrix
B = np.arange(-4,4).reshape(4,2) # 4 by 2 matrix

# einsum

In [9]:
print(einops.einsum(A, B, "i k,k j->i j"))

[[  4  10]
 [-12  10]
 [-28  10]]


# rearrange

In [10]:
print(einops.rearrange(A, "h w -> w h"))

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


# reduce

In [34]:
X = np.arange(12).reshape(3, 4).astype(np.float32)
print(X)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


In [32]:
print(einops.reduce(X, "rows cols -> cols", reduction="mean"))
print()
print(einops.reduce(X, "rows cols -> rows", reduction="mean"))
print()
print(einops.reduce(X, "rows cols -> ", reduction="mean"))
# Keep dimensions
einops.reduce(X, "rows cols -> rows 1", reduction="mean")

[4. 5. 6. 7.]

[1.5 5.5 9.5]

5.5


array([[1.5],
       [5.5],
       [9.5]], dtype=float32)

# repeat

In [46]:
X = np.arange(4)
print(X)

[0 1 2 3]


In [42]:
print(einops.repeat(X, "w -> h w", h = 4))
print()
print(einops.repeat(X, "w -> w 3"))

[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]

[[0 0 0]
 [1 1 1]
 [2 2 2]
 [3 3 3]]


In [45]:
X = np.arange(4).reshape(2, 2)
print(X)

[[0 1]
 [2 3]]


In [44]:
print(einops.repeat(X, "h w -> h (2 w)"))
print()
print(einops.repeat(X, "h w -> h (w 2)"))

[[0 1 0 1]
 [2 3 2 3]]

[[0 0 1 1]
 [2 2 3 3]]
